### ISSUE TITLE
Update for latest build process and tune for default use.

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblock-template#1]
Move content to _sources ?

Add a default warning in README to set the pages build for the repo up front

Package structure documentation so it is referenced and the created bblock doesnt need to hack it it - and it can be updated automatically if the template or post-processing changes - probably a link to a canonical example in the post-process code repo? 

Provide a default link to the generated slate docs

**Comment by avillar** [comment]
I've moved the bblocks to `_sources` and updated some other parts of the template. I've also added instructions to enable GH Pages in the "How to" section. 

If Pages are enabled, Pages URLs will be generated; otherwise, raw.githubusercontent.com ones will be used.
